### ISSUE TITLE
stdout doesn't consistently show on (c)ontinue

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/nextline-graphql#4]
I find that print statements don't consistently show in the web page stdout box if I run the script using the "continue" option. They do show if I step through the program line by line with "next" though.

This can be demonstrated by executing:
```
print('hello world')
```
with both the next and continue buttons.

Perhaps more dramatically with a loop of prints:
```
for i in range(100):
    print(i)
```
In this case I sometimes get 0-3 lines, but the remaining ~97 don't print. Expected output does show in the docker logs on the backend.

**Comment by TaiSakuma** [comment]
The server stops sending the stdout to web clients when a run ends. However, if the script prints a lot or just before it ends, some messages are still in the buffer when the run ends; they won't be sent to web clients.

I found a solution only a few days ago and used it for storing the stdout in the DB. The stdout stored in the DB doesn't have the same problem.

I will apply the same solution for sending the stdout to web clients.

**Comment by TaiSakuma** [comment]
[Nextline 0.1.10](https://pypi.org/project/nextline/0.1.10/), which is required by [Nextline-graphql 0.1.7](https://pypi.org/project/nextline-graphql/0.1.7/), has a quick fix for this issue. It doesn't stop sending stdout when a run ends. It continuously sends stdout [as long as it is written in a thread in which the script is running](https://github.com/simonsobs/nextline/blob/v0.1.10/nextline/main.py#L192-L205), which will be displayed in the web clients. As a side effect, stdout written in threads that are not running the script, for example, written by the API server itself, will no longer be shown in the web client.

**Comment by TaiSakuma** [comment]
I will close this issue. I believe that this is resolved. Please reopen it or open a new issue if the problem still occurs.
